### ISSUE TITLE
This add-on has created too many time-based triggers

### ISSUE THREAD

**Issue by julieelman** [ljay79/jira-tools#53] opened 2018-01-22 21:27 UTC
Hi - I am l looking to use this add-on with my JIRA instance. Today I encountered the following error in Google Docs:

![screen shot 2018-01-22 at 3 09 53 pm](https://user-images.githubusercontent.com/20932356/35243885-638abd16-ff8c-11e7-8daa-4ae40ea1b7a9.png)

> script error: this add-on has created too many time-based triggers in this document for this Google user account in this document

As a note my organization uses Tempo Time Tracking so while I cannot confirm, I am wondering if this could be requiring time-based. Have you encountered this issue before/do you have any recommendations on how to avoid running into this error which is blocking me from importing a full list of JIRA issues? 

Looking forward to hearing back.

**Comment by ljay79** [comment] 2018-01-23 09:56
Hi @julieelman 
this issue sadly is solely caused by my add-on and has nothing to do with any possible Jira plugins like Tempo.
However, i believed i had just few days ago released a fix for this issue.

Explanation of the issue:
When generating a issue list with column "Epic", the add-on uses a time-based trigger, in order to afterwards converting all the Epic cell values into Epic name with Linkto Jira, as i am unable to do this on the fly during list generation due to timing limitations of google sheet apps in general.
However, i (tried) to implement a logic, that it would never create more than 2 of such triggers.

Hmmm..

Can you please make sure, that you have the most recent version of my add-on.
Go to the menu "Add-Ons" -> "Jira Sheet Tools" -> "About".
In the About dialog it will display the current installed version. Should be *v0.20.2*

If this is not the case:
- try uninstall the add-on and install it fresh again from the Add-On Store.

If this is the latest version:
If you like, you can go to the "About" dialog and turn "On" the _Debugging_ . Then please post me your shown "Temp. User Key". This will enable the add-on to log debugging information to my google stack driver account.
It will not log or transfer any sensitive data from the Jira Settings dialog.

Last question: When the issue comes up, try to describe what you exactly try to do, so i might be able to replicate this.
- Jira Cloud instance or self hosted Server?
- used filter would result in approx how many issues (100+, 500+, 1000+, ..?)
- what custom fields did you configure and activated for the issue list?

**Comment by vivida01** [comment] 2018-02-06 13:39
Hello,

I'm also running into this issue with the latest version v0.20.3. 
I am using a self hosted server, filtering ~100 issues,. Custom fields are Epic, Sprint, and Story Points. Something else that may make a difference is the fact that I am using a Google for Work.

For the short term, (assuming everyone is having this issue), I believe it would be better to provide the option to pull in the Epic ID and we could use a lookup in a separate sheet for the actual Epic name. Currently there's no way to get Epic name with this issue.

Thanks!

**Comment by ljay79** [comment] 2018-02-07 10:04
Thanks @vivida01 for your report.

If you like, you can go to the "About" dialog and turn "On" the Debugging . Then please post me your shown "Temp. User Key". This will enable the add-on to log debugging information to my google stack driver account.
It will not log or transfer any sensitive data from the Jira Settings dialog.

Once debugging is active, please reproduce/force the error so i will find it in my logs.
I can then investigate the issue.

**Comment by ljay79** [comment] 2018-02-21 18:35
Hi @julieelman and @julieelman good news i believe.
The latest released and available version 0.21.0 is out.
In this version i have refactored the handling of EPIC fields. Instead of the problem causing time based triggers the add-on is now using a custom function.
This is much more performant and fail safe.

Pls try it out and let me know, if this issue can be considered solved/closed.

**Comment by ljay79** [comment] 2018-03-20 22:19
@julieelman did you give the add-on a second chance? :)

The latest version do handle EPIC data differently now and your mentioned error should not occur anymore.
Please let me know, if this issue is solved and can be solved.

BTW: I would love a rating and feedback for the Add-On in google sheet add-on store.

**Comment by ljay79** [comment] 2018-03-22 21:35
closed and considered  solved given the fact that triggers are refactored and not used in latest versions anymore.

**Closed by ljay79** 2018-03-22 21:35 UTC

**Comment by julieelman** [comment] 2018-05-10 19:29
Thank you for your assistance, I apologize for the delay in getting back to you! I am not currently experiencing this issue. Great work on the Add-On!
