### ISSUE TITLE
Custom functions produce [401 Unauthorized]

### ISSUE THREAD

**Issue by jeffrmanley** [ljay79/jira-tools#123] opened 2019-01-26 22:12 UTC
Setup Jira Tools --> Settings and added Jira instance https and credentials. The run menu driven functions work without any problems. However, when using the custom functions I'm receiving a 401 error. Do the custom functions use the same credentials file or does something else need to be setup?

When using a custom function such as =JST_getTotalForSearchResult("status=done") I receive an Error: [401] - "Unauthorized"

Please help!

Thanks,
Jeff

**Comment by ljay79** [comment] 2019-01-28 13:17
Hi @jeffrmanley 
The entire add-on is using only the details provided at the settings dialog.
An authorization denied error on some parts and not on others, is very strange and new to me.
It usually either works everywhere or nowhere.

For further investigation, please activate Debugging in "About" dialog, provide me with your "Temp. User Key" and then perform at least one another try.
This way it will log the error and debug information to my StackDriver logging account where I can analyze it better.
User credentials are not transmitted in any log data.

**Comment by jeffrmanley** [comment] 2019-01-28 18:44
Hi @ljay79 

The Temp. User Key is - ADKDv6BK5hd5l10fuRuWCO7s+TyY6cZYcbT+4Jxze4s5XwsOVfAF6XVeAjB2+GdjRKB2prQrEXAA

With that same user key I was able to successfully run "List Issues from Filter" from the menu system; however when attempting to run JST_ functions they each errored out.

**Comment by ljay79** [comment] 2019-01-28 20:22
Hi. Very strange. I can see a lot of logs for provided user key. All of which are nice only - debug info, no error, no warning, no auth issue.
To me that indicates, the errorneous calls are not performed with the same scope and not using the proper environment. Dont know really yet how this is even possible.
Will have to investigate the specialities of custom functions further.

QQ:
- Is the sheet this has been performed in, a shared sheet?
- Did you tried performing this procedure/test in a newly created spreadsheet?
- Did you tried to uninstall and re-install the add-on?

PS: If you could perform an error case again pls and this time provide me your exact time you got the error including your timezone. This way i can parse my logs by time rather than by the user key. As more exact the time is, the better. Believe me, i have quite some logs in this StackDriver :(

**Comment by jeffrmanley** [comment] 2019-01-29 13:32
Hi @ljay79 ...I just did another test in a new gSheet at 5:30am PST. 

ERROR receiving now is - TypeError: Funktion replace in Objekt 10 nicht gefunden (line 109). -- this is the first foreign language error I've seen.

=JST_search("project=projrural",10,0)

**Comment by ljay79** [comment] 2019-01-29 18:24
@jeffrmanley  the syntax for _JST_search()_ is wrong.
You missing the second param, a list of fields you want to be returned.

The german error message is a google javascript error message localized by the environment - meaning, it seems you run that function on a german browser or german google spreadsheet. I do not have any influence (that i know of) to interfer with the language of generic JS error. But i sure will be able to catch such parameter usage error and implement better error handling...

**Comment by ljay79** [comment] 2019-02-04 10:38
Close issue as won't fix. Error caused by typo.

**Closed by ljay79** 2019-02-04 10:38 UTC
Labels: bug
