### ISSUE TITLE
Unable to create time report

### ISSUE THREAD

**Issue by coswiz** [ljay79/jira-tools#78] opened 2018-05-16 09:04 UTC
Hello and first of all thanks for developing this tool!

I'm using a Jira server, from where I was able for example to get the list of issues from a filter. 

I encounter an issue when trying to create a time report. Briefly, the user drop-down is not populating and I'm getting the error informing that no users were found to match my search.

Here's the console log: 
`Vn {message: "There was an error during the transport or process…this request. Error code = 10, Path = /wardeninit", name: "TransportError", stack: "TransportError: There was an error during the tran…s/70824026-warden_bin_i18n_warden__ro.js:180:252)"}`

Am I doing something wrong? I am able to get the worklogs using directly the API, so should not be related to user permissions...

Any ideas?

**Comment by ljay79** [comment] 2018-05-16 12:02
Hi @coswiz 

i can only assume an issue due to privacy or api incompatibility to server version for fetching list of users.

Could you please activate Debugging in "About" dialog, provide me your "Temp. User Key" and reproduce the issue.

**Comment by coswiz** [comment] 2018-05-16 14:41
Hi @ljay79, here's the Temp. User Key: AOTQZS3/fm0qmpUfaG67OByCmYqMPlVYYPP/mLtYigigAz0tPAH6E/mIaK0lfCoyBGKMO0euvXOu

**Comment by ljay79** [comment] 2018-05-17 20:36
I took a look and sadly, so far, i could not identify a possible issue or the reason for this.
Pls check permissions to browse users for the account you are using with google sheet.
If its same account you generally use, pls test and see if you get anything returned from the api when you manually call it as follows.

Log on to jira in your browser, then open a new tab in same browser and call following url:
`https://jira-st.stormreply.com/jira/rest/api/2/user/search?username=%25`

When logged on and with correct permissions, you would see some JSON response with data such as usernames etc...
If not authenticated your would only see `[]`

**Comment by coswiz** [comment] 2018-05-18 05:13
Hi @ljay79 , I'm getting an empty json `[]`. I checked also on a local Jira server, where I am an admin, and still the same result...

Most likely this is not possible on the server version? I've found this issue: https://jira.atlassian.com/browse/JRASERVER-29069

Any possible workaround?

**Comment by ljay79** [comment] 2018-05-18 06:58
What version of Jira Server are you using?

**Comment by coswiz** [comment] 2018-05-18 07:07
JIRA v7.6.1

**Comment by coswiz** [comment] 2018-05-22 05:27
Hi @ljay79, `.../jira/rest/api/latest/user/search?username=.` returns some user data.

**Comment by ljay79** [comment] 2018-05-22 07:50
Thx @coswiz will incorporate this soon.
How about Groups, do you get any data when hitting following url: `.../rest/api/2/groups/picker?query=`

**Comment by ljay79** [comment] 2018-05-22 21:13
Updated version with workaround (hope it helps - cant test it here) is now published to GAS.
Pending for approval from google.

**Comment by ljay79** [comment] 2018-05-23 17:37
@coswiz tge updated version is released, pls enable debugging, provide me the user key and try to create a time report for a user. Fingers crossed, you can now select users.

**Comment by lebryk** [comment] 2018-05-23 18:56
@ljay79 Hi. I just installed add-on and have same problem. It is looks like it's still not working correctly. BTW in add-on OVERVIEW before install I see there is version: Jira Sheet Tool v0.23.1 but when I installed and go to "About" dialog the version is v0.23.0

PS: Thanks for your great work with this :)

**Comment by ljay79** [comment] 2018-05-23 19:17
Thx, i can see, it did not really help but there is also another glitch which interfers with my workaround. Have to go another round :) and will update you when ready. Thx for being so patient.

The version in the About dialog is shown from code, as i cant retrieve a real GAS version dynamically.
I always have to update it manually - and this time i forgot it. :)
So you do actually have the latest version.. hehe

**Comment by ljay79** [comment] 2018-05-23 20:58
Have pushed a tweaked update v0.23.2. Lets wait for Google to approve and release it, then please give it another try with debugging on.

**Comment by ljay79** [comment] 2018-05-24 16:46
Awesome, im glad we could get it working. Hope you like the add-on and maybe leave a review inside the GAS (Google Addon Store).

I will close this issue now as solved. Feel free to add further comments or open a new issue when you have any trouble.

**Closed by ljay79** 2018-05-24 16:46 UTC
Labels: JIRA Server, bug
