### ISSUE TITLE
JST_search returns "Error: [-1] - Internal Error! No Jira Settings. (line 147)"

### ISSUE THREAD

**Issue by guenthersehn** [ljay79/jira-tools#79] opened 2018-05-17 13:37 UTC
Hello,

I am using: "=JST_search("status = Done", "key,status", 5)" on A1. Tried many other queries but none work.

However, List from Filter and other stuff, refresh, etc, all work.

Thanks!

Guenther

**Comment by ljay79** [comment] 2018-05-17 20:16
Strange... Did you try closing google sheet and reopen it again, making sure all jira settings are still saved and then perform the search again.

**Comment by ljay79** [comment] 2018-05-18 10:34
Yeah you are right, just wanted to make sure :)

I have currently no slight guess what it could be.
As this error is thrown deep in a generic API Call request which is used for all api requests.
So it should either throw this error everywhere always or never.

Just some thoughts / guesses and questions:
- what Jira service are you using? Cloud or Server? If Server, what version
- is this sheet a shared sheet and maybe uses the Jira settings / credentials of a different user?
- did you try to uninstall and then re-install the add-on

Could you please activate Debugging in "About" dialog, provide me your "Temp. User Key" and reproduce the issue.

**Comment by guenthersehn** [comment] 2018-05-18 11:47
1 - Server
2 - It's shared but it is using my credentials. Actually, I asked someone else to open the spreadsheet, install the add-on, configure for the same Jira but with his credentials, and everything worked exactly like mine (List from filter is working fine, but JST_search is not).
3 - Nope because since the normal List from Filter is working I thought it wouldn't make any difference.

Debug done - AOTQZS3Sj2BVHIM/bFjXbxBzNfFLxqylVGjneVENw8Sto268a+BrfRqhZPtFiiJYd6qugGs8tOLT.

**Comment by ljay79** [comment] 2018-05-18 13:17
Thx for sharing these info.
I can see (for your user key) only successful requests for "list issues from filter". But the described error is not part of it.
I can these error for a different user only.

After you enabled debugging, did you tried the "JST_search()" method?

Please also do uninstall the add-on and reinstall it afterwards again. It wont change / alter your current sheet, so dont be afraid to loose any sheet data.

**Comment by guenthersehn** [comment] 2018-05-18 13:50
Yes, I executed after debug was turned on.

I also uninstalled the addon, closed the spreadsheet, opened, reinstalled, etc, but it didn't work.

BUT, I just created a blank spreadsheet, inserted the JST_search and... it worked. So right no, in the new spreadsheet it works, and in the other one it doesn't regardless if I create new sheets or not.

**Comment by ljay79** [comment] 2018-05-18 15:16
Can you remember, how the Add-on was used first time with the non-working sheet?
Did you yourself created a new spreadsheet and installed the add-on yourself or did someone else...

It seems as something got mixed up during share, setup and so on.
Its just a very rough though but its very strange its isoleted in 1 spreadsheet for you and that i can see your successfull logs under a fully different user session in the logs compared to the session with the errors.

I have to investigate further and hope you might be available from time to time if any assistance is needed.

Thx for hanging out so long, and i am half relieved, you found at least a way (new spreadsheet) to get it working.

**Comment by guenthersehn** [comment] 2018-05-18 16:04
Yes I will try to figure out what's going on. Anyway, I just found out this query is limited on 100 records, which doesn't work for me... I need more. Basically what I really want to have is one simple sheet with all my jira tickets and fields so I can do some VLOOKUPS and QUERIES in other sheets... and I wanted to create a button or something to easy update the Jira list anytime I want. With this funcion JST_search I thought I was going to be able to it, since everytime I wanted everything updated I could just hit the Recalculate All Formulas. Being able to hit a button/macro would be nice too.

**Comment by ljay79** [comment] 2018-05-18 16:36
I can feel your pain, after all this trouble now it works but it isnt what you need.
This little query function is however limited to 100 results max. To get more, the filter feature is your best bet atm.

Read more about hte limitations and reasons here: [README](https://github.com/ljay79/jira-tools#jst_search)

**Comment by guenthersehn** [comment] 2018-05-18 17:30
No problem, your plugin is already helping me.
The filter works for me, the biggest problem is having to thru “Add-ons" > “Jira Sheet Tools” > "List Issues from Filter" every time, and select fields again, etc. I just needed a way to execute that in a more automated way.

**Comment by ljay79** [comment] 2018-05-18 18:08
Yeah, im with you but some of the limitations of google also did surprise me even i technically understand them.
I dont know how many jira issues you intend to import and how many columns, but we could workaround it.
Would it help, when you would be able to define a start position in the JST_search() because then you could create one sheet, with multiple JST_search queries side by side. Manually pagination lets say.
Through the autoupdate you are then able to update everything at once and aggregate what you need in another sheet.
However: You might still expirience or reach limits from google for timeouts or amount of data pulled etc.. Google sheet seems just not built for such heavy duty.

Even better would be, if you could do the aggregation directly in the search query or via combination of filter and queries rather then trying to import entire JIRA database / heavy data sets and then aggregate them in sheets.

**Comment by guenthersehn** [comment] 2018-05-18 18:21
Yes, I think that would be great if we can add start position in the function.... then I can run as many as I need, put them all inside a query, etc. In my specific case, I won't need more than 1000 lines probably.

**Comment by ljay79** [comment] 2018-05-20 20:50
Hi @guenthersehn 
i actually was able to find one way to reproduce such issue and aso understand now why.
Cant tell for sure if this is reason of yours but im pretty sure.

Custom functions in google work quite different then the rest of an add-on script. It has other auth scopes and different lifecycle.

I noticed; the custom functions basically are owned by the user who owns the spreadsheet.
If the spreadsheet is owned by user A and installs the add-on - but did *not* authorized or configured Jira yet (or wrong jira settings), the user B who as access to same spreadsheet will expirience your above mentioned errors on the custom functions.
When user B installs and configured the Jira Sheet Tools add-on, he however will be able to use all features sources via the menu - but not the custom functions.

Its therefor very important that the owner of such spreadsheet, intending to use Jira Sheet Tools add-on and shares to other users, make sure to configure the add-on correctly. Otherwise the other users wont be able to use the custom functions.

I have not been able to find or think of a solution for this, but i might need to highlight and document this in the Readme somehow.

**Comment by ljay79** [comment] 2018-05-20 20:53
PS: Please be aware, that when the sheets are shared, other users might be able to interfer with the custom functions / data output from them as all subsequent data is always fetched by using the current users credentials.

Sample:
JST_search() will always return the result of the user running the function at a time, updating the sheet, opening it or using re-calculate and overwrites data from other users results.

**Comment by guenthersehn** [comment] 2018-05-23 15:55
Hey! Just wanted to report your changes worked very well by doing something like this:

={
JST_search("filter=myfilter", "key,summary,duedate,assignee,status", 100, 0);
JST_search("filter=myfilter", "key,summary,duedate,assignee,status", 100, 100);
...
}

Then it works just like if it was only one call. My next goal dive deeper and see if there is anyway to automate this "command repeat" that I have to do manually. Anyway, it's working! (yay!)

The only weird thing is that I configured "myfilter" with a "ORDER BY key ASC" inside Jira, but the result returned by the function is in the opposite order, so I had to actually repeat it again righter after the filter, like this "filter=myfilter ORDER BY key ASC", then it returned everything in the order I needed.

On extra suggestion? Implement a JST_count_search() just to return the total records count. I am using like that thru an additional add on.

Thanks a LOT!

Guenther

**Comment by ljay79** [comment] 2018-05-23 19:38
Great to hear that im getting closer to make you satisfied :)

### Filter sort
I didnt researched much about this yet, but i can tell you that the JQL is passed to JIRA api straight without interferring with it. As such i believe that the api is ignoring sort definition of stored filter.
If this is intended or an bug in the api, i will have to research.

### Long click path..
As mentioned before, take a look at Google Sheets new MACRO feature. In your Spreadsheet menu "Tools". Didnt tried it yet, but it sounds like it would offer what you are looking for.

### JST_count_search()
You should really have a look at my [README](https://github.com/ljay79/jira-tools#jst_gettotalforsearchresult) :)
... or in any cell start typing `=JST_`, it will reveal a function `JST_getTotalForSearchResult()`.

I consider this issue as solved and will close it, but feel free to comment on it.
Im also happy when you might submit a review within the GAS marketplace.

**Closed by ljay79** 2018-05-23 19:38 UTC
