### ISSUE TITLE
Can't connect to self-hosted Jira - Error 500

### ISSUE THREAD

**Issue by narvek** [ljay79/jira-tools#89] opened 2018-06-22 17:52 UTC
We have a self hosted Jira.  I've used our https address to try to connect, using the user/pw that I use to connect to Jira, but am receiving an error 500.  I've turned on debugging, Temp. User Key:
AG3SVdnnYwlEEf4WhKu29b2uQYtqi6g5yLPvqVoETwdUBtEQuXPV4iCepMnr5ymV8ErcULHRYW1j

**Comment by ljay79** [comment] 2018-06-24 13:57
Hi @narvek 

Are you trying to connect to your Jira instance with URL _https://jira.sccoe.org/_ ?
This appears to be a not publicly routed domain.
I am getting DNS errors when trying to open it in a browser.

Google add-ons (like this here) will only work with public hosted and reachable services.

**Comment by narvek** [comment] 2018-06-25 04:48
Oh my. Yes you are right. Will have to see if I can white list. Thanks. And apologies for such a rookie mistake.

On Jun 24, 2018, 6:57 AM -0700, Jens <notifications@github.com>, wrote:

Hi @narvek<https://github.com/narvek>

Are you trying to connect to your Jira instance with URL https://jira.sccoe.org/ ?
This appears to be a not publicly routed domain.
I am getting DNS errors when trying to open it in a browser.

Google add-ons (like this here) will only work with public hosted and reachable services.

**Comment by phyllisz** [comment] 2018-06-28 21:43
Hi,
  I have this same error. My colleague was able to get it setup but I'm getting this error 500. 

temp user key: AG3SVdlne3SKQiqDRg/LBAlKA4bhCWoxgRQZMwWXNN7fRiy2FzDaoY7eQSSPvXlotQlKcegUKT8b

**Comment by ljay79** [comment] 2018-06-29 07:42
Hi @phyllisz 

I personally never saw a Jira cloud domain like "https://xxxx.jira.com".
What version of Jira are you guys running under that domain?

Your colleague is using the same Jira instance? May you ask him how he did connect successfully - using what settings and maybe even share the feedback here with me and other potential users with same issue.

**Comment by phyllisz** [comment] 2018-06-29 23:36
hmmm not sure, I can't find a version number for our JIRA cloud, I would assume it's just whatever latest is available since it's constantly updated from Atlassian. 

Yup, we are using the same. I went over the setup with him and we put in the same values (aside from email/pswd). 

Am I putting in the pswd wrong? 
I write it [email]+[password] - and various combinations. I also tried the API token.

**Comment by ljay79** [comment] 2018-06-30 10:39
To test the authentification with your Jira instance via curl, you can check the output of this:
```sh
curl -D- -u <email>:<password> -X GET -H "Content-Type: application/json" "https://<xxxx>.jira.com/rest/api/2/dashboard"
```

Another thing:
To check if this issue is caused by your user account, have your colleage come over and test the connection with his login details. Afterwards you can remove the details again.

**Comment by ljay79** [comment] 2018-08-29 15:44
@phyllisz did you had any luck yet? And further insight? Other wise i would close this issue.

**Comment by phyllisz** [comment] 2018-09-04 18:38
Hi,
  Nope didn't make any progress. I'll give it another try this week.

**Comment by tcorman** [comment] 2018-11-01 14:56
We're having the same 500 error with JIRA in the cloud. What's really odd is that it's specific to one user - the rest of us are configured identically and have no problem using Sheets Tools. One use, who is having no problems accessing JIRA in the browser, gets the 500 error when she attempts to configure Sheet Tools settings. Should the diagnostic curl command about work against a cloud JIRA instance?

**Comment by ljay79** [comment] 2018-11-01 16:39
Hi @tcorman 

The above curl command would give a good indication of wether authentication for her works through api, yes.
`curl -D- -u <email>:<password> -X GET -H "Content-Type: application/json" "https://<xxxx>.jira.com/rest/api/2/dashboard"`

For further insight from my end, (on the affected users google sheet) please activate Debugging in "About" dialog, provide the your "Temp. User Key" and then perform at least one another try.
This way it will log possible errors and information to my StackDriver logging account where i can analyze it better.
User credentials are not transmitted in any log data.

**Comment by tcorman** [comment] 2018-11-28 21:18
OK, issues persists,  curl command works fine for both me and the user who is experiencing the 500 error. She has enabled debugging, I can send you her temp key if that helps.

**Comment by tcorman** [comment] 2018-11-29 17:00
I'm confused, though - if username/password was the issue, wouldn't the curl command fail?

**Comment by ljay79** [comment] 2018-11-29 17:33
@tcorman yeah you're right lol. Confusing my self...  as you figured, i dont have any further clue what the issue could be.

In case you are firm, you can try same curl command with username/password encrypted base64 for basic auth. As this is the way, the add-on will request the api.

**Comment by ljay79** [comment] 2018-11-29 17:35
@tcorman you tried uninstalling / reinstalling the add-on already?

And to be sure, the 500 error appears during editing the settings in my add-on, not somewhere else?

**Comment by ljay79** [comment] 2018-11-30 09:56
Just in case you guys didnt tried yet... for curiosity...

The troubling user, should create a own personal completely new spreadsheet. No sharing.
Then reinstall the add-on, and try to setup connection etc...

I can only guess there is some strange auth behavior when accessing a shared sheet with the add-on installed. Otherwise i really dont have a clue anymore what the cause could be.

The add-on performs basic simple HTTP(S) requests to the Jira instance using google [UrlFetchApp.fetch](https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app)

**Comment by ljay79** [comment] 2018-11-30 11:46
Everyone still having the error 500 issue, please provide me with the Temp User key from the add-on's "About" dialog and perform at least 1 try of saving the connection settings for Jira.
Thx

**Comment by tcorman** [comment] 2018-11-30 16:57
Is it ok to post Temp Key here in the clear?

Yes, uninstalled/reinstalled, no change. I and one other user are having no problems - it's specific to this one user, but her JIRA privileges are the same as ours.

**Comment by ljay79** [comment] 2018-11-30 20:32
Yes it should be fine to post this key here. Only use I know of, is for identification in my stack driver logs.

**Comment by tcorman** [comment] 2018-12-04 22:03
Temp key for user w issues: 
AEt9bgQ1QVmAmKy6HmmHbm+Kqp9K9GSCE+qWbqrcrVd1wYcSJKq/TnGxlr8YoOle00Xu1ytVJfZB

**Comment by ljay79** [comment] 2019-01-07 14:43
Sry @tcorman, i was on annual vacation in december and then the seasons holidays.
Im not "back in business".

Could you please redo the debugging steps with the affected user:
- enable debugging
- re-post temp user key (it changes frequently)
- perform troubling request and report here again, best: with a timeframe which i can check logs in

Thx and appologies for late reply and delay.

**Comment by tcorman** [comment] 2019-01-07 19:16
@ljay79 Thanks - will do Wed afternoon, and will post here.

**Comment by tcorman** [comment] 2019-01-09 21:19
Just enabled debugging. Her temp user key:
AFzpkEQix9mAzB+UdvMBBWUC8lrImRdd7Oxcn0yqr3VIYcsnhho4vR5Uf9JRCt9v5uzKGOl/6zaX
Tried request at ~1:12 PM Pacific with user ctrese using a Sheet that I own:
List issues from filter displays dialog, then returns "Exception: SSL Error https://vlocity.attlassian.net/rest/api/2/filter/favourite?includeFavourites=true"
Works fine for me.

Next experiment: user ctrese creates a Sheet and chooses "List Issues from filter." Dialog displays but hangs populating a list of the filters she owns.

That's all we tried - let me know how we can provide more debug details. Thanks for your help!

**Comment by ljay79** [comment] 2019-01-10 09:09
Thank you, the error lies in the posted error message and the logs do confirm this.

In best case; it was really just this simply typo:
The URL for (her) Jira instances used is incorrect. "*Atlassian'" is written with a single "t" and not like she/you wrote and used it with double "t".

I hope it was just as simple issue as this :)

**Comment by ljay79** [comment] 2019-01-15 20:35
@tcorman any news? Issue solved?

**Comment by ljay79** [comment] 2019-01-22 21:01
Assumes fixed. Closed due to inactivity.

**Closed by ljay79** 2019-01-22 21:01 UTC
Labels: question
